### PR TITLE
Convert to setuptool package

### PR DESCRIPTION
**Pull request by flux1on**
Restructure code so that you can install do `pip install .` and import the project easily

### CODE REVIEW

**Comment by flux1on** [comment]
Added some a small section to the README on how to install. Also added some dependencies I missed originally.

**Comment by iGio90** [comment]
I cant merge this atm, conflict with config.py, register.py and uddbg.py.
Do you want me to look into this?

**Comment by flux1on** [comment]
Sure. The conflicts should be pretty minor.

**Comment by flux1on** [comment]
Done in #10, so closing

**Pull request closed without merging**
