### PR TITLE
Proper Rebase and example for setuptools

### PR DESCRIPTION
**Pull request by domenukk**
This rebases #8 (great work there) and changes the example to use the setuptools version.

### CODE REVIEW

**Comment by iGio90** [comment]
can I close the other one?

**Comment by iGio90** [comment]
superthanks! i had no time to look into it those days :( superbusy preparing a keynote

**Comment by domenukk** [comment]
> 
> 
> can I close the other one?

Yes, cc @flux1on

**Comment by flux1on** [comment]
Thanks for rebasing properly.

**Pull request merged**
